apiVersion: v1
kind: Service
metadata:
  name: fitness-app-service
spec:
  selector:
    app: fitness-app
  type: LoadBalancer # Creates a public IP address and load balancer in Azure
  ports:
  - protocol: TCP
    port: 80 # The public port people will access
    targetPort: 3000 # The internal port your container listens on
